2021-08-21 00:40:41,581 ERROR: Exception on /explore [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 160, in explore
    next_url=next_url, prev_url=prev_url)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 11, in block 'app_content'
    {% include '_post.html' %}
  File "/Users/vajo/local/job/microblog/app/templates/_post.html", line 5, in top-level template code
    <img src="{{ post.author.avatar(70) }}" />
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'avatar'
2021-08-21 00:41:01,649 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:51]
2021-08-21 00:41:03,880 ERROR: Exception on /index [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 30, in index
    posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 11, in block 'app_content'
    {% include '_post.html' %}
  File "/Users/vajo/local/job/microblog/app/templates/_post.html", line 5, in top-level template code
    <img src="{{ post.author.avatar(70) }}" />
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email().encode('utf-8')).hexdigest()
TypeError: 'str' object is not callable
2021-08-21 00:41:23,340 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:51]
